In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Data Types and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], [3.4,5.6,6.7]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [3.4, 5.6, 6.7]])

In [6]:
a3 = np.array([[[1,2,3], 
                [4,5,6], 
                [7,8,9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3[0, 1,1]

5

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a dataFrame from Numpy

In [16]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  3.4  5.6  6.7

In [17]:
## 2. Create a numpy array
sa1 = np.array([1,2,3])
sa1

array([1, 2, 3])

In [18]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
a4 = np.ones((3,3))*5
a4

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [21]:
a5 = np.arange(0,11)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a5 = np.arange(0,11,2)
a5

array([ 0,  2,  4,  6,  8, 10])

In [23]:
a6 = np.random.randint(0,20, size = (4,5))
a6

array([[ 4, 17, 14,  3, 10],
       [ 9,  5,  9,  6,  0],
       [ 3, 14,  4, 17,  3],
       [ 5,  7,  2, 16, 15]])

In [24]:
a7 = np.random.random((5,3))
a7 

array([[0.57760678, 0.72571443, 0.61790146],
       [0.23418484, 0.33650794, 0.12371208],
       [0.68520864, 0.50628207, 0.13517243],
       [0.68690901, 0.46074369, 0.71813648],
       [0.86484811, 0.9291348 , 0.4556342 ]])

In [25]:
a8 = np.random.rand(5,3)
a8

array([[0.13287683, 0.7953044 , 0.90014258],
       [0.09334817, 0.47278753, 0.92602111],
       [0.61145337, 0.84706244, 0.47676575],
       [0.00762425, 0.82623518, 0.26426449],
       [0.72529174, 0.55379624, 0.8277667 ]])

In [26]:
# Pseudo random numbers
np.random.seed(0)
a9 = np.random.randint(10, size = (5,3))
a9

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [27]:
np.random.seed(0)
a10 = np.random.random((5,3))
a10

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## Viewing Array and Matrices

In [28]:
np.unique(a9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2. , 3. ],
       [3.4, 5.6, 6.7]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a1[0]

1

In [33]:
a2[1,1]

5.6

In [34]:
a3[1,1,2]

15

In [35]:
a3[1,2,:2]

array([16, 17])

In [36]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
a11 = np.random.randint(10, size = (2,3,4,5))
a11

array([[[[9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7],
         [0, 1, 9, 9, 0]],

        [[4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1]],

        [[7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4],
         [4, 3, 4, 4, 8]]],


       [[[4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2],
         [4, 2, 0, 3, 2]],

        [[0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4]],

        [[6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2],
         [3, 2, 0, 8, 8]]]])

In [38]:
a11.shape, a11.ndim

((2, 3, 4, 5), 4)

In [39]:
a11[1,1,0,0:4]

array([0, 7, 5, 9])

In [40]:
a11[:,:,:,:4]

array([[[[9, 4, 3, 0],
         [5, 0, 2, 3],
         [1, 3, 3, 3],
         [0, 1, 9, 9]],

        [[4, 7, 3, 2],
         [2, 0, 0, 4],
         [5, 6, 8, 4],
         [4, 9, 8, 1]],

        [[7, 9, 9, 3],
         [7, 2, 0, 3],
         [9, 4, 4, 6],
         [4, 3, 4, 4]]],


       [[[4, 3, 7, 5],
         [0, 1, 5, 9],
         [0, 5, 0, 1],
         [4, 2, 0, 3]],

        [[0, 7, 5, 9],
         [2, 7, 2, 9],
         [3, 3, 2, 3],
         [1, 2, 9, 1]],

        [[6, 8, 2, 3],
         [0, 6, 0, 6],
         [3, 8, 8, 8],
         [3, 2, 0, 8]]]])

In [41]:
a11[:,:,:,:3]

array([[[[9, 4, 3],
         [5, 0, 2],
         [1, 3, 3],
         [0, 1, 9]],

        [[4, 7, 3],
         [2, 0, 0],
         [5, 6, 8],
         [4, 9, 8]],

        [[7, 9, 9],
         [7, 2, 0],
         [9, 4, 4],
         [4, 3, 4]]],


       [[[4, 3, 7],
         [0, 1, 5],
         [0, 5, 0],
         [4, 2, 0]],

        [[0, 7, 5],
         [2, 7, 2],
         [3, 3, 2],
         [1, 2, 9]],

        [[6, 8, 2],
         [0, 6, 0],
         [3, 8, 8],
         [3, 2, 0]]]])

In [42]:
a11[:,:,:,:2]

array([[[[9, 4],
         [5, 0],
         [1, 3],
         [0, 1]],

        [[4, 7],
         [2, 0],
         [5, 6],
         [4, 9]],

        [[7, 9],
         [7, 2],
         [9, 4],
         [4, 3]]],


       [[[4, 3],
         [0, 1],
         [0, 5],
         [4, 2]],

        [[0, 7],
         [2, 7],
         [3, 3],
         [1, 2]],

        [[6, 8],
         [0, 6],
         [3, 8],
         [3, 2]]]])

In [43]:
a11[:,:,:,:1]

array([[[[9],
         [5],
         [1],
         [0]],

        [[4],
         [2],
         [5],
         [4]],

        [[7],
         [7],
         [9],
         [4]]],


       [[[4],
         [0],
         [0],
         [4]],

        [[0],
         [2],
         [3],
         [1]],

        [[6],
         [0],
         [3],
         [3]]]])

## Manipulating and comparing Arrays


### Arithmetic 

In [44]:
a1

array([1, 2, 3])

In [45]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [47]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [48]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [49]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 3.4, 11.2, 20.1]])

In [50]:
a1/ones

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [51]:
a2/a1

array([[1.        , 1.        , 1.        ],
       [3.4       , 2.8       , 2.23333333]])

In [52]:
a2//a1

array([[1., 1., 1.],
       [3., 2., 2.]])

In [53]:
a2**2

array([[ 1.  ,  4.  ,  9.  ],
       [11.56, 31.36, 44.89]])

In [54]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [11.56, 31.36, 44.89]])

In [55]:
a2**3

array([[  1.   ,   8.   ,  27.   ],
       [ 39.304, 175.616, 300.763]])

In [56]:
a2 % 2

array([[1. , 0. , 1. ],
       [1.4, 1.6, 0.7]])

In [57]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [58]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Aggregation = preparing the same operation on a number of things

In [59]:
l1 = np.array([1,2,3])
l1

array([1, 2, 3])

In [60]:
np.sum(l1)

6

In [66]:
ma = np.random.random(100000)

In [67]:
len(ma)

100000

In [68]:
ma.sum()

49955.59760527885

In [70]:
ma1 = np.random.random(10)
ma1

array([0.87863886, 0.76680462, 0.39979513, 0.24851335, 0.03043538,
       0.77255815, 0.73953937, 0.54434284, 0.82291795, 0.97261967])

In [71]:
sum(ma)

49955.59760528004

In [72]:
np.sum(ma)

49955.59760527885

In [76]:
%timeit sum(ma) # Python sum
%timeit np.sum(ma) # Numpy sum

30.5 ms ± 609 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
82.6 µs ± 18.4 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [77]:
a2

array([[1. , 2. , 3. ],
       [3.4, 5.6, 6.7]])

In [78]:
np.mean(a2)

3.6166666666666667

In [79]:
np.max(a2)

6.7

In [80]:
np.std(a2)

1.9718152944826135

In [81]:
np.std(a2, axis = 1)

array([0.81649658, 1.37194104])

In [82]:
np.var(a2)

3.8880555555555554

In [83]:
np.sqrt(np.var(a2))

1.9718152944826135