In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Data Types and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], [3.4,5.6,6.7]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [3.4, 5.6, 6.7]])

In [6]:
a3 = np.array([[[1,2,3], 
                [4,5,6], 
                [7,8,9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3[0, 1,1]

5

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a dataFrame from Numpy

In [16]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  3.4  5.6  6.7

In [17]:
## 2. Create a numpy array
sa1 = np.array([1,2,3])
sa1

array([1, 2, 3])

In [18]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
a4 = np.ones((3,3))*5
a4

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [21]:
a5 = np.arange(0,11)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a5 = np.arange(0,11,2)
a5

array([ 0,  2,  4,  6,  8, 10])

In [23]:
a6 = np.random.randint(0,20, size = (4,5))
a6

array([[ 2, 11, 19,  4, 13],
       [ 6, 11, 19, 11, 11],
       [ 0, 18,  8,  7, 16],
       [ 2, 19, 12, 16, 17]])

In [24]:
a7 = np.random.random((5,3))
a7 

array([[0.82782833, 0.3500435 , 0.9110983 ],
       [0.13492341, 0.77293078, 0.62163997],
       [0.29860805, 0.20898276, 0.35601724],
       [0.40412551, 0.7358487 , 0.41435894],
       [0.61712115, 0.06236927, 0.21152591]])

In [25]:
a8 = np.random.rand(5,3)
a8

array([[0.60431981, 0.55842124, 0.75259378],
       [0.3479694 , 0.13085833, 0.38007791],
       [0.47437314, 0.24951881, 0.3885801 ],
       [0.68351104, 0.85170542, 0.43227561],
       [0.25680087, 0.65720615, 0.63372932]])

In [31]:
# Pseudo random numbers
np.random.seed(0)
a9 = np.random.randint(10, size = (5,3))
a9

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [35]:
np.random.seed(0)
a10 = np.random.random((5,3))
a10

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])