In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Data Types and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], [3.4,5.6,6.7]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [3.4, 5.6, 6.7]])

In [6]:
a3 = np.array([[[1,2,3], 
                [4,5,6], 
                [7,8,9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3[0, 1,1]

5

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a dataFrame from Numpy

In [16]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  3.4  5.6  6.7

In [17]:
## 2. Create a numpy array
sa1 = np.array([1,2,3])
sa1

array([1, 2, 3])

In [18]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
a4 = np.ones((3,3))*5
a4

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [21]:
a5 = np.arange(0,11)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a5 = np.arange(0,11,2)
a5

array([ 0,  2,  4,  6,  8, 10])

In [23]:
a6 = np.random.randint(0,20, size = (4,5))
a6

array([[13,  2,  1, 11, 19],
       [17,  3,  6, 10, 12],
       [17,  2, 13,  8,  0],
       [18,  0,  6,  4, 19]])

In [24]:
a7 = np.random.random((5,3))
a7 

array([[0.17149686, 0.75043754, 0.4280593 ],
       [0.79299003, 0.1854174 , 0.15999382],
       [0.97911184, 0.66874875, 0.74890253],
       [0.59213228, 0.97531236, 0.47356131],
       [0.47144598, 0.06643142, 0.82002028]])

In [25]:
a8 = np.random.rand(5,3)
a8

array([[0.9669814 , 0.53229429, 0.95836398],
       [0.85260776, 0.55888065, 0.00826518],
       [0.21487619, 0.63697869, 0.31928498],
       [0.07376095, 0.83695019, 0.32552529],
       [0.21428866, 0.25288476, 0.71191577]])

In [26]:
# Pseudo random numbers
np.random.seed(0)
a9 = np.random.randint(10, size = (5,3))
a9

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [27]:
np.random.seed(0)
a10 = np.random.random((5,3))
a10

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## Viewing Array and Matrices

In [28]:
np.unique(a9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2. , 3. ],
       [3.4, 5.6, 6.7]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1[0]

1

In [35]:
a2[1,1]

5.6

In [36]:
a3[1,1,2]

15

In [37]:
a3[1,2,:2]

array([16, 17])

In [40]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [45]:
a11 = np.random.randint(10, size = (2,3,4,5))
a11

array([[[[6, 7, 2, 3, 1],
         [9, 5, 9, 9, 2],
         [0, 9, 1, 9, 0],
         [6, 0, 4, 8, 4]],

        [[3, 3, 8, 8, 7],
         [0, 3, 8, 7, 7],
         [1, 8, 4, 7, 0],
         [4, 9, 0, 6, 4]],

        [[2, 4, 6, 3, 3],
         [7, 8, 5, 0, 8],
         [5, 4, 7, 4, 1],
         [3, 3, 9, 2, 5]]],


       [[[2, 3, 5, 7, 2],
         [7, 1, 6, 5, 0],
         [0, 3, 1, 9, 9],
         [6, 6, 7, 8, 8]],

        [[7, 0, 8, 6, 8],
         [9, 8, 3, 6, 1],
         [7, 4, 9, 2, 0],
         [8, 2, 7, 8, 4]],

        [[4, 1, 7, 6, 9],
         [4, 1, 5, 9, 7],
         [1, 3, 5, 7, 3],
         [6, 6, 7, 9, 1]]]])

In [46]:
a11.shape, a11.ndim

((2, 3, 4, 5), 4)

In [54]:
a11[1,1,0,0:4]

array([7, 0, 8, 6])

In [57]:
a11[:,:,:,:4]

array([[[[6, 7, 2, 3],
         [9, 5, 9, 9],
         [0, 9, 1, 9],
         [6, 0, 4, 8]],

        [[3, 3, 8, 8],
         [0, 3, 8, 7],
         [1, 8, 4, 7],
         [4, 9, 0, 6]],

        [[2, 4, 6, 3],
         [7, 8, 5, 0],
         [5, 4, 7, 4],
         [3, 3, 9, 2]]],


       [[[2, 3, 5, 7],
         [7, 1, 6, 5],
         [0, 3, 1, 9],
         [6, 6, 7, 8]],

        [[7, 0, 8, 6],
         [9, 8, 3, 6],
         [7, 4, 9, 2],
         [8, 2, 7, 8]],

        [[4, 1, 7, 6],
         [4, 1, 5, 9],
         [1, 3, 5, 7],
         [6, 6, 7, 9]]]])

In [58]:
a11[:,:,:,:3]

array([[[[6, 7, 2],
         [9, 5, 9],
         [0, 9, 1],
         [6, 0, 4]],

        [[3, 3, 8],
         [0, 3, 8],
         [1, 8, 4],
         [4, 9, 0]],

        [[2, 4, 6],
         [7, 8, 5],
         [5, 4, 7],
         [3, 3, 9]]],


       [[[2, 3, 5],
         [7, 1, 6],
         [0, 3, 1],
         [6, 6, 7]],

        [[7, 0, 8],
         [9, 8, 3],
         [7, 4, 9],
         [8, 2, 7]],

        [[4, 1, 7],
         [4, 1, 5],
         [1, 3, 5],
         [6, 6, 7]]]])

In [59]:
a11[:,:,:,:2]

array([[[[6, 7],
         [9, 5],
         [0, 9],
         [6, 0]],

        [[3, 3],
         [0, 3],
         [1, 8],
         [4, 9]],

        [[2, 4],
         [7, 8],
         [5, 4],
         [3, 3]]],


       [[[2, 3],
         [7, 1],
         [0, 3],
         [6, 6]],

        [[7, 0],
         [9, 8],
         [7, 4],
         [8, 2]],

        [[4, 1],
         [4, 1],
         [1, 3],
         [6, 6]]]])

In [60]:
a11[:,:,:,:1]

array([[[[6],
         [9],
         [0],
         [6]],

        [[3],
         [0],
         [1],
         [4]],

        [[2],
         [7],
         [5],
         [3]]],


       [[[2],
         [7],
         [0],
         [6]],

        [[7],
         [9],
         [7],
         [8]],

        [[4],
         [4],
         [1],
         [6]]]])